/* Generated by automated build script */
#define RELEASE 0.81
//PuTTYAttach
//#define TEXTVER "Release 0.81"
#define TEXTVER "(pipPuTTY)Release 0.81"
//
#define SSHVER "-Release-0.81"
#define BINARY_VERSION 0,81,0,0
